export default {
  Oval: (
    <svg xmlns="http://www.w3.org/2000/svg" width="220" height="75">
      <g>
        <ellipse
          stroke="#000"
          ry="15"
          rx="25"
          id="svg_3"
          cy="35.8"
          cx="27"
          fill="#fff"
        />
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_6"
          y="29.8"
          x="100"
          stroke="#000"
          fill="#000000"
        >
          Branch (US)
        </text>
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_7"
          y="46.8"
          x="108"
          stroke="#000"
          fill="#000000"
        >
          Branch (Local)
        </text>
      </g>
    </svg>
  ),
  Rectangle: (
    <svg xmlns="http://www.w3.org/2000/svg" width="220" height="75">
      <g>
        <rect
          stroke="#000"
          x="7"
          y="21"
          width="41"
          height="29"
          fill="#fff"
        />
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_6"
          y="29.8"
          x="110"
          stroke="#000"
          fill="#000000"
        >
          Corporation (US)
        </text>
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_7"
          y="46.8"
          x="118"
          stroke="#000"
          fill="#000000"
        >
          Corporation (Local)
        </text>
      </g>
    </svg>
  ),
  Triangle: (
    <svg xmlns="http://www.w3.org/2000/svg" width="220" height="75">
      <g>
        <rect
          stroke="#000"
          id="svg_1"
          height="79"
          width="140"
          y="102.4"
          x="78.6"
          fill="#fff"
        />
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_6"
          y="29.8"
          x="110"
          stroke="#000"
          fill="#000000"
        >
          Partnership (US)
        </text>
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_7"
          y="46.8"
          x="118"
          stroke="#000"
          fill="#000000"
        >
          Partnership (Local)
        </text>
        <path
          stroke="#000"
          id="svg_10"
          d="m9.955,48.29161l19.5,-32l19.5,32l-39,0z"
          fill="#000000"
        />
      </g>
    </svg>
  ),
  "Triangle-Rectangle": (
    <svg xmlns="http://www.w3.org/2000/svg" width="220" height="75">
      <g>
        <rect
          id="svg_13"
          height="25"
          width="41"
          y="24.29999"
          x="6"
          stroke="#0f0f00"
          fill="#ffffff"
        />
        <rect
          stroke="#000"
          id="svg_1"
          height="79"
          width="140"
          y="102.4"
          x="78.6"
          fill="#fff"
        />
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_6"
          y="29.8"
          x="110"
          stroke="#000"
          fill="#000000"
        >
          Partnership (US)
        </text>
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_7"
          y="46.8"
          x="118"
          stroke="#000"
          fill="#000000"
        >
          Corporation (Local)
        </text>
        <path
          stroke="#0f0f00"
          id="svg_14"
          d="m5.935,49.27162l20.5,-24l20.5,24l-41,0z"
          fill="#ffffff"
        />
      </g>
    </svg>
  ),
  "Oval-Rectangle": (
    <svg xmlns="http://www.w3.org/2000/svg" width="220" height="75">
      <g>
        <rect
          id="svg_13"
          height="25"
          width="41"
          y="26.29999"
          x="6"
          stroke="#0f0f00"
          fill="#ffffff"
        />
        <rect
          stroke="#000"
          id="svg_1"
          height="79"
          width="140"
          y="102.4"
          x="78.6"
          fill="#fff"
        />
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_6"
          y="32.8"
          x="110"
          stroke="#000"
          fill="#000000"
        >
          Disregarded (US)
        </text>
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_7"
          y="48.8"
          x="118"
          stroke="#000"
          fill="#000000"
        >
          Corporation (Local)
        </text>
        <ellipse
          stroke="#0f0f00"
          ry="12"
          rx="19"
          id="svg_15"
          cy="39.29999"
          cx="26"
          fill="#ffffff"
        />
      </g>
    </svg>
  ),
  "Inv-Triangle-Rectangle": (
    <svg xmlns="http://www.w3.org/2000/svg" width="220" height="75">
      <g>
        <rect
          id="svg_13"
          height="25"
          width="41"
          y="24.29999"
          x="6"
          stroke="#0f0f00"
          fill="#ffffff"
        />
        <rect
          stroke="#000"
          id="svg_1"
          height="79"
          width="140"
          y="102.4"
          x="78.6"
          fill="#fff"
        />
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_6"
          y="32.8"
          x="110"
          stroke="#000"
          fill="#000000"
        >
          Corporation (US)
        </text>
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_7"
          y="48.8"
          x="118"
          stroke="#000"
          fill="#000000"
        >
          Partnership (Local)
        </text>
        <path
          transform="rotate(180 26.435 36.7716)"
          stroke="#0f0f00"
          id="svg_14"
          d="m5.935,49.27162l20.5,-25l20.5,25l-41,0z"
          fill="#ffffff"
        />
      </g>
    </svg>
  ),
  "Oval-Triangle": (
    <svg xmlns="http://www.w3.org/2000/svg" width="220" height="75">
      <g>
        <rect
          stroke="#000"
          id="svg_1"
          height="79"
          width="140"
          y="102.4"
          x="78.6"
          fill="#fff"
        />
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_6"
          y="32.8"
          x="110"
          stroke="#000"
          fill="#000000"
        >
          Disregarded (US)
        </text>
        <text
          textAnchor="start"
          fontSize="7.5"
          strokeWidth="0"
          id="svg_7"
          y="48.8"
          x="118"
          stroke="#000"
          fill="#000000"
        >
          Partnership (Local)
        </text>
        <path
          stroke="#0f0f00"
          id="svg_14"
          d="m5.935,48.27162l20.5,-23l20.5,23l-41,0z"
          fill="#ffffff"
        />
        <ellipse
          stroke="#0f0f00"
          ry="7"
          rx="10.5"
          id="svg_17"
          cy="40.29999"
          cx="26.5"
          fill="#ffffff"
        />
      </g>
    </svg>
  )
}
